name: ci-sonarcloud
on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          fetch-depth: 0
          node-version: 16.0
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test -coverprofile=coverage.out
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}